---
permalink: deploy/concept_space_and_sizing_requirements_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: VMware vSphere용 ONTAP 툴을 구축하기 전에 구축 패키지에 대한 공간 요구 사항과 몇 가지 기본 호스트 시스템 요구 사항을 숙지해야 합니다. 
---
= ONTAP 툴 구축 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴을 구축하기 전에 구축 패키지에 대한 공간 요구 사항과 몇 가지 기본 호스트 시스템 요구 사항을 숙지해야 합니다.

ONTAP 툴을 Windows vCenter Server 또는 VMware vCSA(vCenter Server 가상 어플라이언스)와 함께 사용할 수 있습니다. ESXi 시스템이 포함된 지원되는 vSphere에 ONTAP 툴을 구축해야 합니다.

* * 노드별 설치 패키지 공간 요구 사항 *
+
** 씬 프로비저닝된 설치의 경우 10GB
** 일반 프로비저닝 설치의 경우 200GB


* * 노드당 호스트 시스템 크기 조정 요구 사항 *
배포 크기와 노드별 권장 메모리는 아래 표와 같습니다.


|===


| 배포 유형입니다 | CPU입니다 | 메모리(GB) 


| 소형(S) | 8 | 16 


| 중간(M) | 12 | 24 


| 크게(L) | 16 | 32 
|===


== 최소 스토리지 및 애플리케이션 요구사항:

|===
| 스토리지, 호스트 및 애플리케이션 | 버전 요구 사항 


| ONTAP | ONTAP 9.10.1, 9.11, 9.12 및 9.13 


| VMware vSphere를 참조하십시오 | 지원되는 최소 VMware 버전은 7.0.3입니다. 


| ESXi 호스트 | ESXi 7.0.3 이상 버전 


| vCenter Server입니다 | vCenter 7.0.3을 참조하십시오 


| VASA 공급자 | 3.0 


| OVA 응용 프로그램 | 10.0 
|===
상호 운용성 매트릭스 툴(IMT)에는 지원되는 ONTAP 버전, vCenter Server, ESXi 호스트 및 플러그인 애플리케이션에 대한 최신 정보가 포함되어 있습니다.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["상호 운용성 매트릭스 툴"^]



== 추가 구축 고려 사항

배포 ONTAP 도구를 사용자 지정하는 동안 몇 가지 요구 사항을 고려해야 합니다.



=== 응용 프로그램 사용자 암호입니다

관리자 계정에 할당된 암호입니다. 보안상의 이유로 암호 길이는 8-30자로, 최소 1자, 1자, 1자리, 1개의 특수 문자를 포함하는 것이 좋습니다. 암호가 90일 후에 만료됩니다.



=== 어플라이언스 유지 관리 콘솔 자격 증명

"성자" 사용자 이름을 사용하여 유지보수 콘솔에 액세스해야 합니다. 배포 중에 "성자" 사용자의 암호를 설정할 수 있습니다. ONTAP 도구의 유지 관리 콘솔에 있는 응용 프로그램 구성 메뉴를 사용하여 암호를 변경할 수 있습니다.



=== vCenter Server IP 주소입니다

* ONTAP 툴을 등록할 vCenter Server 인스턴스의 IP 주소(IPv4)를 제공해야 합니다.
+
생성되는 ONTAP 툴 및 VASA 인증서의 유형은 구축 중에 제공한 IP 주소(IPv4)에 따라 다릅니다.

* vCenter Server에 등록하는 데 사용되는 ONTAP 툴 IP 주소는 구축 마법사에 입력한 vCenter Server IP 주소(IPv4)의 유형에 따라 다릅니다.
+
ONTAP 툴과 VASA 인증서는 모두 vCenter Server 등록 중에 사용되는 것과 동일한 유형의 IP 주소를 사용하여 생성됩니다.

* 설치 중에 VM이 마이그레이션되지 않도록 합니다.
+

NOTE: VMware vSphere 10.0 릴리즈용 ONTAP 툴에서는 IPv6가 지원되지 않습니다.





=== 어플라이언스 네트워크 속성입니다

유효한 DNS 호스트 이름(비정규화)과 ONTAP 도구 및 기타 네트워크 매개 변수의 정적 IP 주소를 지정합니다. DHCP는 VMware vSphere 10.0 릴리즈용 ONTAP 툴에서 지원되지 않습니다. 이러한 매개 변수는 모두 올바른 설치 및 작동에 필요합니다.
