---
permalink: deploy/prepare_deployment.html 
sidebar: sidebar 
keywords:  
summary: 어플라이언스를 사용하려면 사용자 환경에 ONTAP 툴을 구축하고 필요한 매개 변수를 지정해야 합니다. 
---
= ONTAP 툴을 배포할 준비를 합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴은 VASA Provider를 포함하는 다중 vCenter Server를 지원합니다.

VMware vSphere용 ONTAP 툴을 구축하기 전에 기본 스토리지 백엔드 요구 사항, 애플리케이션 요구 사항 및 라이센스 요구 사항을 숙지해야 합니다.
VMware vSphere용 ONTAP 툴을 구축하기 전에 구축을 계획하고 사용자 환경에서 ONTAP 툴을 구성하는 방법을 결정하는 것이 좋습니다.



== 배포 준비 중

다음은 구축을 계속하기 위한 ONTAP 툴 요구 사항입니다.

* vCenter Server 환경을 구성하고 설정합니다.
* _.ova_file을 다운로드합니다.
* OVA가 배포된 호스트 또는 리소스 풀에 * ONTAP 도구 구축을 위한 요구 사항 * 섹션에 언급된 최소 리소스가 있는지 확인합니다.
* 브라우저 캐시를 삭제합니다.
* 로드 밸런서와 Kubernetes API Server에 두 개의 가상 IP가 필요합니다. 배포 후 서비스에 액세스하는 데 사용되는 배포에 사용되는 VLAN에서 두 개의 무료 IP를 가져옵니다.
* 상용 CA에서 CA 인증서(루트, 리프 및 중간 인증서)를 조달합니다.
* 사용자 지정 CA 인증서가 필요한 다중 vCenter 배포의 경우 인증서가 발급되는 * 도메인 이름 * 을 * 가상 IP * 에 매핑합니다. 도메인 이름에 대해 ping 검사를 수행하여 도메인이 의도된 IP로 확인되는지 확인합니다.
* NFS를 사용하는 ONTAP의 스토리지 VM이 필요합니다. 다음 단계에 따라 스토리지 VM을 구성합니다.
+
** ONTAP System Manager와 ONTAP CLI를 모두 열어야 합니다.
** 새 스토리지 VM을 생성하려면 ONTAP System Manager에 로그인하여 NFS가 활성화된 스토리지 VM을 생성하십시오.
** 100GB 이상의 애그리게이트를 추가합니다.
** Aggregate가 성공적으로 추가되었는지 확인하려면 다음을 수행합니다.
+
a) ONTAP CLI에 로그인합니다

+
b) vserver show -fields aggr-list 명령을 실행합니다

+
c) 기본 스토리지 VM에 대해 Aggregate가 나열되지 않은 경우 다음 명령을 실행합니다. vserver modify <storage VM name> -aggr -list <aggregate name>

+
기본 스토리지 VM에 추가할 애그리게이트의 이름을 찾으려면 ONTAP CLI에서 _aggr show_를 사용합니다

+
이 명령은 스토리지 시스템의 애그리게이트 목록을 표시하며 * Aggregate * 열에서 사용해야 하는 애그리게이트의 이름을 찾을 수 있습니다.

** 구축 구성에는 두 가지 옵션이 있습니다. 하나는 클러스터 자격 증명, 다른 하나는 SVM 자격 증명 또는 직접 SVM입니다. 직접 SVM의 경우 구축을 시작하기 전에 SVM에 대한 관리 LIF를 구성해야 합니다. 클러스터 자격 증명에 대해서는 이 단계를 건너뜁니다.
** 네트워크 경로가 존재하는지 확인하고 ONTAP CLI에 로그인하여 network route show -vserver <storage vm name> 명령을 실행합니다
+
존재하지 않는 경우, ONTAP CLI에 로그인하여 다음 명령을 실행합니다. net route create-vserver <vserver name>-destination <destination IP>-gateway <gateway IP>-metric 20

** 스토리지 VM에 대한 엑스포트 정책이 있는지 확인합니다. ONTAP 시스템 관리자에서 * 스토리지 * > * 스토리지 VM * > * [스토리지 VM 이름] * > * 설정 * > * 엑스포트 정책 * 으로 이동합니다. 내보내기 정책이 없으면 다음 단계를 따르십시오.
** ONTAP CLI에서 다음 명령을 사용하여 엑스포트 정책 규칙을 생성합니다
+
vserver export-policy rule create -vserver <스토리지 VM 이름> -policyname <엑스포트 정책 이름> -clientmatch <ESXI-IP> -rorule any -rwrule any -superuser any

+

NOTE: superuser_value가 _none_이 아닌지 확인하십시오.




