---
permalink: concepts/concept_configure_vvols_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'VASA Provider for ONTAP를 사용하여 VMware 가상 볼륨(VVol\)을 생성하고 관리할 수 있습니다. VVOL 데이터 저장소를 프로비저닝, 편집, 마운트 및 삭제할 수 있습니다. 또한 스토리지를 VVOL 데이터 저장소에 추가하거나 VVOL 데이터 저장소에서 스토리지를 제거하여 유연성을 향상할 수도 있습니다.' 
---
= VVOL을 위한 VASA 공급자 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP용 VASA Provider를 사용하여 VMware 가상 볼륨(VVol)을 생성 및 관리할 수 있습니다. VVOL 데이터 저장소를 프로비저닝, 편집, 마운트 및 삭제할 수 있습니다. 또한 스토리지를 VVOL 데이터 저장소에 추가하거나 VVOL 데이터 저장소에서 스토리지를 제거하여 유연성을 향상할 수도 있습니다.

VVOL 데이터 저장소는 스토리지 컨테이너 내에 있는 하나 이상의 FlexVol 볼륨으로 구성됩니다(백업 스토리지라고도 함). 가상 머신은 하나의 VVol 데이터 저장소 또는 여러 개의 VVol 데이터 저장소에 분산될 수 있습니다.

여러 개의 FlexVol 볼륨이 있는 VVol 데이터 저장소를 생성할 수 있지만, 스토리지 컨테이너 내의 모든 FlexVol 볼륨은 동일한 프로토콜(NFS 또는 iSCSI)과 동일한 SVM(스토리지 가상 머신)을 사용해야 합니다.


NOTE: 성능 및 유연성을 위해 VVOL 데이터 저장소에 여러 FlexVol 볼륨을 포함하는 것이 좋습니다. FlexVol 볼륨에는 여러 FlexVol 볼륨을 비롯한 가상 머신 수를 제한하는 LUN 개수 제한이 있기 때문에 VVOL 데이터 저장소에 더 많은 가상 머신을 저장할 수 있습니다. 다양한 볼륨을 추가하면 데이터 저장소 기능이 향상되어 씬 볼륨과 일반 볼륨이 혼합되어 데이터 저장소에 두 종류의 VM을 모두 생성할 수 있습니다.

VASA Provider는 가상 머신 프로비저닝 또는 VMDK 생성 중에 다양한 유형의 VVOL을 생성합니다.

* * 구성 *
+
VMware vSphere는 이 VVOL 데이터 저장소를 사용하여 구성 정보를 저장합니다.

+
SAN(블록) 구축에서 스토리지는 4GB LUN입니다.
vCenter 8은 씬 프로비저닝에서 256GB LUN의 용량을 사용합니다.

+
NFS 구축에서 vmx 파일과 같은 VM 구성 파일 및 다른 VVol 데이터 저장소에 대한 포인터와 같은 디렉토리가 포함된 디렉토리입니다.

* * 데이터 *
+
이 VVOL에는 운영 체제 정보 및 사용자 파일이 포함되어 있습니다.

+
SAN 구축에서 가상 디스크의 크기인 LUN입니다.

+
NFS 구현에서 이는 가상 디스크의 크기인 파일입니다.

* * 교환 *
+
이 VVol은 가상 머신의 전원을 켜면 생성되고 가상 머신의 전원을 끄면 삭제됩니다.

+
SAN 구축에서 이 LUN은 가상 메모리의 크기입니다.

+
NFS 구현에서 이는 가상 메모리의 크기를 가진 파일입니다.

* * 메모리 *
+
VM 스냅샷을 생성할 때 메모리 스냅샷 옵션을 선택하면 이 VVol이 생성됩니다.

+
SAN 구축에서 이 LUN은 가상 메모리의 크기입니다.

+
NFS 구현에서 이는 가상 메모리의 크기를 가진 파일입니다.


