---
permalink: concepts/concept_vcenter_server_role_based_access_control_features_in_vsc_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'vCenter Server는 vSphere 객체에 대한 액세스를 제어할 수 있도록 역할 기반 액세스 제어(RBAC)를 제공합니다.' 
---
= ONTAP 도구의 역할 기반 액세스 제어 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter Server는 vSphere 객체에 대한 액세스를 제어할 수 있도록 역할 기반 액세스 제어(RBAC)를 제공합니다. vCenter Server는 역할 및 권한이 있는 사용자 및 그룹 권한을 사용하여 인벤토리에서 다양한 수준으로 중앙 집중식 인증 및 권한 부여 서비스를 제공합니다. vCenter Server에는 RBAC 관리를 위한 5가지 주요 구성 요소가 있습니다.

|===


| 구성 요소 | 설명 


| 권한 | 권한은 vSphere에서 작업을 수행하기 위한 액세스를 설정하거나 거부합니다. 


| 역할 | 역할에는 하나 이상의 시스템 권한이 포함되며, 여기서 각 권한은 시스템의 특정 개체 또는 개체 유형에 대한 관리 권한을 정의합니다. 사용자에게 역할을 할당하면 사용자는 해당 역할에 정의된 권한의 기능을 상속합니다. 


| 사용자 및 그룹 | 사용자 및 그룹은 AD(Active Directory) 또는 로컬 Windows 사용자/그룹에서도 역할을 할당할 수 있는 사용 권한에 사용됩니다(권장하지 않음). 


| 권한 | 사용 권한을 통해 사용자 또는 그룹에 특정 작업을 수행하고 vCenter Server 내의 객체를 변경할 수 있는 권한을 할당할 수 있습니다. vCenter Server 사용 권한은 ESXi 호스트에 직접 로그인하는 사용자가 아니라 vCenter Server에 로그인하는 사용자에게만 영향을 줍니다. 


| 오브젝트 | 작업이 수행되는 엔티티입니다. VMware vCenter 객체는 데이터 센터, 폴더, 리소스 풀, 클러스터, 호스트, 및 VM을 지원합니다 
|===
작업을 성공적으로 완료하려면 적절한 vCenter Server RBAC 역할이 있어야 합니다. 작업 중에 ONTAP 툴은 사용자의 ONTAP 권한을 확인하기 전에 사용자의 vCenter Server 역할을 확인합니다.


NOTE: vCenter Server 역할은 관리자가 아닌 ONTAP 툴 vCenter 사용자에게 적용됩니다. 기본적으로 관리자는 제품에 대한 모든 액세스 권한을 가지며 할당된 역할이 필요하지 않습니다.

사용자 및 그룹은 vCenter Server 역할의 일부가 되어 역할에 액세스할 수 있습니다.



== vCenter Server에 대한 역할 할당 및 수정에 대한 주요 사항

vSphere 객체 및 작업에 대한 액세스를 제한하려는 경우에만 vCenter Server 역할을 설정해야 합니다. 그렇지 않으면 관리자로 로그인할 수 있습니다. 이 로그인을 통해 모든 vSphere 객체에 자동으로 액세스할 수 있습니다.

역할을 할당하는 위치에 따라 사용자가 수행할 수 있는 ONTAP 도구 작업이 결정됩니다. 언제든지 하나의 역할을 수정할 수 있습니다.
역할 내의 권한을 변경하는 경우 해당 역할과 연결된 사용자는 로그아웃한 다음 다시 로그인하여 업데이트된 역할을 사용하도록 설정해야 합니다.



== ONTAP 툴과 함께 패키지로 제공되는 표준 역할입니다

ONTAP 툴은 vCenter Server 권한 및 RBAC 작업을 간소화하기 위해 주요 ONTAP 툴 작업을 수행할 수 있는 표준 ONTAP 툴 역할을 제공합니다. 또한 정보를 볼 수는 있지만 작업을 수행할 수 없는 읽기 전용 역할도 있습니다.

vSphere 클라이언트 홈 페이지에서 * 역할 * 을 클릭하여 ONTAP 툴 표준 역할을 볼 수 있습니다. ONTAP 도구에서 제공하는 역할을 사용하여 다음 작업을 수행할 수 있습니다.

|===


| * 역할 * | * 설명 * 


| NetApp ONTAP 도구 관리자 | 일부 ONTAP 툴 작업을 수행하는 데 필요한 모든 기본 vCenter Server 권한 및 ONTAP 툴별 권한을 제공합니다. 


| NetApp ONTAP 도구 읽기 전용 | ONTAP 도구에 대한 읽기 전용 액세스를 제공합니다. 이러한 사용자는 액세스가 제어되는 ONTAP 도구 작업을 수행할 수 없습니다. 


| NetApp ONTAP 툴 프로비저닝  a| 
에는 스토리지 용량 할당에 필요한 몇 가지 기본 vCenter Server 권한 및 ONTAP 툴별 권한이 나와 있습니다. 다음 작업을 수행할 수 있습니다.

* 새 데이터 저장소를 생성합니다
* 데이터 저장소를 관리합니다


|===
Manager UI 관리자 역할이 vCenter에 등록되지 않았습니다. 이 역할은 관리자 UI에 따라 다릅니다.

회사에서 표준 ONTAP 도구 역할보다 제한적인 역할을 구현해야 하는 경우 ONTAP 도구 역할을 사용하여 새 역할을 만들 수 있습니다.

이 경우 필요한 ONTAP 도구 역할을 클론한 다음 사용자에게 필요한 권한만 있도록 클론 생성된 역할을 편집합니다.



== ONTAP 스토리지 백 엔드 및 vSphere 객체에 대한 권한

vCenter Server 권한이 충분하면 ONTAP 툴이 스토리지 백엔드 자격 증명(사용자 이름 및 암호)과 연결된 ONTAP RBAC 권한(ONTAP 역할)을 확인합니다. 해당 스토리지 백엔드에서 해당 ONTAP 툴 작업에 필요한 스토리지 작업을 수행할 수 있는 충분한 권한이 있는지 확인합니다. 올바른 ONTAP 권한이 있는 경우 에 액세스할 수 있습니다
스토리지 백엔드로 ONTAP 툴 작업을 수행합니다. ONTAP 역할에 따라 스토리지 백엔드에서 수행할 수 있는 ONTAP 툴 작업이 결정됩니다.
