---
permalink: configure/task_configure_user_role_and_privileges.html 
sidebar: sidebar 
keywords: user roles 
summary: ONTAP 툴과 ONTAP System Manager와 함께 제공되는 JSON 파일을 사용하여 스토리지 백엔드 관리를 위한 새로운 사용자 역할을 구성할 수 있습니다. 
---
= 사용자 역할 및 권한을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 툴 및 ONTAP System Manager와 함께 제공되는 JSON 파일을 사용하여 스토리지 백엔드 관리를 위한 새로운 사용자 역할 및 권한을 구성할 수 있습니다.

* 필요한 것 *

* 을 사용하여 ONTAP 도구에서 ONTAP 권한 파일을 다운로드해야 합니다 `\https://<loadbalancerIP>:8443/virtualization/user-privileges/users_roles.zip`.
+

NOTE: 클러스터 또는 직접 스토리지 가상 머신(SVM) 레벨에서 사용자를 생성할 수 있습니다. user_roles.json 파일을 사용하지 않고 사용자를 생성할 수도 있습니다. 생성한 경우 SVM 레벨에서 최소 권한 세트가 있어야 합니다.

* 스토리지 백엔드에 대한 관리자 권한으로 로그인해야 합니다.


* 단계 *

. 다운로드한 파일의 압축을 풉니다 `\https://<loadbalancerIP>:8443/virtualization/user-privileges/users_roles.zip` 파일.
. ONTAP 시스템 관리자에 액세스합니다. ONTAP System Manager에 액세스하려면 클러스터의 클러스터 관리 IP를 사용합니다.
. 클러스터 또는 SVM 사용자로 로그인합니다.
. 클러스터 * > * 설정 * > * 사용자 및 역할 * 창을 선택합니다.
. 사용자 아래에서 * 추가 * 를 선택합니다.
. 사용자 추가 * 대화 상자에서 * 가상화 제품 * 을 선택합니다.
. ONTAP 권한 JSON 파일을 선택하고 업로드하려면 * 찾아보기 * 를 선택하십시오.
+
제품 필드가 자동으로 채워집니다.

. 제품 기능 드롭다운 메뉴에서 필요한 기능을 선택합니다.
+
역할 * 필드는 선택한 제품 기능에 따라 자동으로 채워집니다.

. 필요한 사용자 이름과 암호를 입력합니다.
. 사용자에게 필요한 권한(검색, 스토리지 생성, 스토리지 수정, 스토리지 제거, NAS/SAN 역할)을 선택한 다음 * 추가 * 를 클릭합니다.


새 역할 및 사용자가 추가되고 구성한 역할 아래에서 자세한 권한을 볼 수 있습니다.


NOTE: 제거 작업을 수행해도 ONTAP 도구 역할은 제거되지 않지만 ONTAP 도구별 권한에 대한 지역화된 이름은 제거되고 접두사가 추가됩니다 `XXX missing privilege` 있습니다. ONTAP 도구를 다시 설치하거나 최신 버전의 ONTAP 도구로 업그레이드하면 모든 표준 ONTAP 도구 역할 및 ONTAP 도구별 권한이 복원됩니다.



== SVM 애그리게이트 매핑 요구사항

데이터 저장소 프로비저닝에 직접 SVM 자격 증명을 사용하기 위해 내부 ONTAP 툴은 데이터 저장소 POST API에 지정된 애그리게이트에서 볼륨을 생성합니다. ONTAP에서는 직접 SVM 자격 증명을 사용하여 SVM에서 매핑되지 않은 애그리게이트에 볼륨을 생성할 수 없습니다. 이 문제를 해결하려면 여기에서 설명하는 대로 REST API 또는 CLI를 사용하여 SVM을 애그리게이트와 매핑해야 합니다.

REST API:

[listing]
----
PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"aggregates":{"name":["aggr1","aggr2","aggr3"]}}'
----
ONTAP CLI:

[listing]
----
sti115_vsim_ucs630f_aggr1 vserver show-aggregates                                        AvailableVserver        Aggregate      State         Size Type    SnapLock Type-------------- -------------- ------- ---------- ------- --------------svm_test       sti115_vsim_ucs630f_aggr1                               online     10.11GB vmdisk  non-snaplock
----


== ONTAP 사용자 및 역할을 수동으로 생성합니다

JSON 파일을 사용하지 않고 수동으로 사용자 및 역할을 생성하려면 이 섹션의 지침을 따르십시오.

. ONTAP 시스템 관리자에 액세스합니다. ONTAP System Manager에 액세스하려면 클러스터의 클러스터 관리 IP를 사용합니다.
. 클러스터 또는 SVM 사용자로 로그인합니다.
. 클러스터 * > * 설정 * > * 사용자 및 역할 * 창을 선택합니다.
. 역할 생성:
+
.. 역할 * 표 아래에서 * 추가 * 를 선택합니다.
.. 역할 이름 * 및 * 역할 속성 * 세부 정보를 입력합니다.
+
REST API 경로 * 및 드롭다운에서 각 액세스를 추가합니다.

.. 필요한 모든 API를 추가하고 변경 사항을 저장합니다.


. 사용자 생성:
+
.. 사용자 * 표에서 * 추가 * 를 선택합니다.
.. 사용자 추가 * 대화 상자에서 * 시스템 관리자 * 를 선택합니다.
.. 사용자 이름 * 을 입력합니다.
.. 위의 * 역할 생성 * 단계에서 생성한 옵션에서 * 역할 * 을 선택합니다.
.. 액세스 권한을 부여할 응용 프로그램과 인증 방법을 입력합니다. ONTAPI 및 HTTP는 필수 응용 프로그램이며 인증 유형은 * Password * 입니다.
.. 사용자의 * 비밀번호 * 를 설정하고 사용자를 * 저장 * 합니다.






== 관리자가 아닌 전역 범위 클러스터 사용자에게 필요한 최소 권한 목록입니다

사용자 JSON 파일을 사용하지 않고 생성된 관리자가 아닌 전역 범위 클러스터 사용자에게 필요한 최소 권한은 이 섹션에 나와 있습니다.
클러스터가 로컬 범위에 추가되는 경우 ONTAP에서 프로비저닝하기 위한 읽기 권한 이상의 권한이 ONTAP 도구에 필요하므로 JSON 파일을 사용하여 사용자를 생성하는 것이 좋습니다.

API 사용:

|===


| API를 참조하십시오 | 액세스 수준 | 에 사용됩니다 


| /api/클러스터 | 읽기 전용 | 클러스터 구성 검색 


| /api/cluster/licensing/licenses 를 선택합니다 | 읽기 전용 | 라이센스 확인 - 프로토콜별 라이센스 


| /api/cluster/nodes를 사용합니다 | 읽기 전용 | 플랫폼 유형 검색 


| /api/스토리지/애그리게이트 | 읽기 전용 | 데이터 저장소/볼륨 프로비저닝 중 애그리게이트 공간 검사 


| /api/storage/cluster 를 선택합니다 | 읽기 전용 | 클러스터 수준 공간 및 효율성 데이터를 가져오는 데 사용됩니다 


| /api/스토리지/디스크 | 읽기 전용 | Aggregate에 연결된 Disks를 가져옵니다 


| /api/스토리지/QoS/정책 | 읽기/생성/수정 | QoS 및 VM 정책 관리 


| /api/svm/sSVM | 읽기 전용 | 클러스터가 로컬에 추가된 경우 SVM 구성을 가져옵니다. 


| /api/network/ip/interfaces 를 참조하십시오 | 읽기 전용 | 스토리지 백엔드 추가 - 관리 LIF 범위가 클러스터/SVM으로 식별됩니다 


| /API 를 참조하십시오 | 읽기 전용 | 클러스터 사용자는 올바른 스토리지 백엔드 상태를 가져오려면 이 권한이 있어야 합니다. 그렇지 않으면 ONTAP 툴 관리자 UI에 "알 수 없는" 스토리지 백엔드 상태가 표시됩니다. 
|===