---
permalink: manage/manage_vcenter.html 
sidebar: sidebar 
keywords:  
summary: vCenter는 호스트, 가상 머신 및 스토리지 백엔드를 제어할 수 있는 중앙 관리 플랫폼입니다. 
---
= vCenter 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter는 호스트, 가상 머신 및 스토리지 백엔드를 제어할 수 있는 중앙 관리 플랫폼입니다.



== vCenter를 추가합니다

하나의 VMware vCenter 10.0용 ONTAP 툴 인스턴스를 사용하여 여러 vCenter를 추가하고 관리할 수 있습니다.

* 단계 *

. 을 시작합니다 `\https://loadBalanceIP:8443/virtualization/ui/` 구축하는 동안 제공된 ONTAP 도구 관리자 자격 증명을 사용하여 브라우저에서
. 사이드바에서 vCenter를 선택합니다
. vCenter IP 주소/호스트 이름, 사용자 이름, 암호 및 포트가 있는 온보드 vCenter에 * 추가 * 를 선택합니다.
. 스토리지 백엔드 * 페이지로 이동하여 호스트 이름, 사용자 이름, 암호 및 포트가 있는 * 온보드 스토리지 백엔드에 추가 * (ONTAP 클러스터)를 선택합니다.


을 참조하십시오 link:../configure/task_configure_user_role_and_privileges.html["관리자가 아닌 전역 범위 클러스터 사용자에게 필요한 최소 권한 목록입니다"].



== vCenter에 스토리지 백엔드를 연결하거나 분리합니다

vCenter 목록 페이지에는 연결된 스토리지 백엔드 수가 표시됩니다. 각 vCenter에는 스토리지 백엔드 연결 또는 연결 해제 옵션이 있습니다
이 작업은 스토리지 백엔드와 온보딩된 vCenter 간의 매핑을 생성하는 데 도움이 됩니다.

* 단계 *

. 을 시작합니다 `\https://loadBalanceIP:8443/virtualization/ui/` 구축하는 동안 제공된 ONTAP 도구 관리자 자격 증명을 사용하여 브라우저에서
. 사이드바에서 vCenter를 선택합니다.
. 스토리지 백엔드와 연결하거나 분리할 vCenter에 대해 세로 줄임표를 클릭합니다.
. 수행할 작업에 따라 * 스토리지 백엔드 연결 또는 연결 해제 * 를 선택합니다.
+
을 참조하십시오 link:../configure/task_configure_user_role_and_privileges.html["관리자가 아닌 전역 범위 클러스터 사용자에게 필요한 최소 권한 목록입니다"].





== vCenter 수정

아래 단계에 따라 vCenter를 수정합니다.

. 을 시작합니다 `\https://loadBalanceIP:8443/virtualization/ui/` 구축하는 동안 제공된 ONTAP 도구 관리자 자격 증명을 사용하여 브라우저에서
. 사이드바에서 vCenter를 선택합니다
. 수정할 vCenter에 대한 세로 줄임표를 클릭하고 * Modify * 를 선택합니다.
. vCenter 세부 정보를 수정하고 * Modify * 를 선택합니다.




== vCenter를 제거합니다

제거하기 전에 vCenter에 연결된 모든 스토리지 백엔드를 제거해야 합니다.

. 을 시작합니다 `\https://loadBalanceIP:8443/virtualization/ui/` 구축하는 동안 제공된 ONTAP 도구 관리자 자격 증명을 사용하여 브라우저에서
. 사이드바에서 vCenter를 선택합니다
. 제거하려는 vCenter에 대한 세로 줄임표를 클릭하고 * Remove * 를 선택합니다.
+

NOTE: vCenter를 제거하면 애플리케이션에서 더 이상 유지 관리하지 않습니다.





== 스토리지 임계값 관리

다음 Get Threshold API를 사용하여 볼륨 및 애그리게이트에 대해 구성된 스토리지 임계값 제한을 검색합니다.

[listing]
----
GET​/virtualization​/api​/v1​/vcenters​/{vcguid}​/storage-thresholds
----
예:
vCenter GUID를 기준으로 vCenter당 스토리지 임계값을 가져옵니다

[listing]
----
GET "/api/v1/vcenters/beded9ad-6bbb-4c9e-b4c6-691250bfe2da/storage-thresholds"
----
구성된 임계값 제한에 도달하면 다음 패치 구성 알람을 사용하여 볼륨 및 애그리게이트에 대해 알림을 생성합니다.

[listing]
----
PATCH​/virtualization​/api​/v1​/vcenters​/{vcguid}​/storage-thresholds
----
예:
vCenter GUID를 기준으로 vCenter당 스토리지 임계값을 업데이트합니다. 기본 한도는 거의 가득 찬 경우 80%, 가득 찬 경우 90%입니다.
모든 임계값 설정 수정

[listing]
----
{{{}PATCH "/api/v1/vcenters/beded9ad-6bbb-4c9e-b4c6-691250bfe2da/storage-thresholds"
Request Body
{
"volume":

{ "nearly_full_percent": 80, "full_percent": 90 }
,
"aggregate": {
"nearly_full_percent": 80,
"full_percent": 90
}
}{}}}{}
----